apiVersion: v1
kind: Service
metadata:
  name: nodeport-dev
spec:
  type: NodePort
  selector:
    app: myapp-dev #we used this for deployment. Service identifies the pod using this
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32004
